### ISSUE TITLE
Spacing around UI elements

### ISSUE THREAD

**Issue by dyc3** [dyc3/d6-survey-service#96]
Currently, stuff is squished together.

![image](https://user-images.githubusercontent.com/1808807/222914468-9a60d169-05d4-468e-b86b-171400adaca0.png)

This is pretty hard to read, so we need to space stuff out.

**Comment by nick-dimeglio** [comment]
I can't get access to the test survey for the life of me; is there something else besides cargo run that has to be initialized?

**Comment by nick-dimeglio** [comment]
It is throwing a problem that lodash cannot be found as a module even after ensuring all packages were up to date and specifically checking lodash.

**Comment by dyc3** [comment]
Our dev databases are not synchronized. We don't have any database seeding mechanism. You will need to create and edit a survey with the fields and questions you need.

You are capable of doing this using the insomnia config I posted in the gc, with minor modifications. Another great tool in your tool belt here would be beekeeper studio for directly viewing the contents of postgres.
